name: GREAT MESSANGING APP
description: A GREAT MESSANGING APP WITH STREAMING FACILITY.
version: 1.2.4.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  stream_chat_flutter: ^0.2.2
  http: ^0.122.0+990
  cupertino_icons: ^0.2.3

dev_dependencies:
  GREATMESSANGING _TEST:
    sdk: flutter

flutter:
  uses-material-design: true
